name = "b2b"
main = "src/index.js"
compatibility_date = "2025-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_database"
database_id = "60aee100-e9ad-462b-a406-191d5e502b6c"

# Environment variables
[vars]
ENVIRONMENT = "development"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "b2b-product-images"

[[kv_namespaces]]
binding = "STATIC_ASSETS" #
id = "475279d00ff34494b551ef3377741f67" # 从 Cloudflare 获取的 KV Namespace ID
